/* eslint-disable quote-props */
/* eslint-disable max-len */
/**
 * Translation file for this resource.
 *
 * This file is generated by combining automatic extraction and manual translations:
 * - The "en" (English) section is automatically extracted from source files
 * - Other language sections can be manually translated or pulled from Transifex
 * - When regenerating, existing manual translations are preserved when the English
 *   source text hasn't changed
 *
 * Structure:
 * - interface: translations for name/description (used by GUI formatMessage)
 * - extensions: translations for extension blocks (used by VM formatMessage)
 * - blocks: translations for Blockly blocks (used by Blockly.Msg)
 */

export default {
    'interface': {
        'en': {
            'microPythonEsp32.description': 'Wi-Fi & Bluetooth control board with rich functions.'
        },
        'ru': {
            'microPythonEsp32.description': 'Wi-Fi & Bluetooth control board with rich functions.'
        },
        'zh-cn': {
            'microPythonEsp32.description': '功能强大且带有 Wi-Fi 和蓝牙的控制板。'
        },
        'zh-tw': {
            'microPythonEsp32.description': 'Wi-Fi & Bluetooth control board with rich functions.'
        }
    },
    'extensions': {
        'en': {
            'microPythonEsp32.modeMenu.input': 'input',
            'microPythonEsp32.modeMenu.output': 'output',
            'microPythonEsp32.modeMenu.inputPullup': 'input-pullup',
            'microPythonEsp32.modeMenu.inputPulldown': 'input-pulldown',
            'microPythonEsp32.levelMenu.high': 'high',
            'microPythonEsp32.levelMenu.low': 'low',
            'microPythonEsp32.InterrupModeMenu.risingEdge': 'rising edge',
            'microPythonEsp32.InterrupModeMenu.fallingEdge': 'falling edge',
            'microPythonEsp32.InterrupModeMenu.changeEdge': 'change edge',
            'microPythonEsp32.InterrupModeMenu.low': 'low level',
            'microPythonEsp32.InterrupModeMenu.high': 'high level',
            'microPythonEsp32.eolMenu.warp': 'warp',
            'microPythonEsp32.eolMenu.noWarp': 'no-warp',
            'microPythonEsp32.category.pins': 'Pins',
            'microPythonEsp32.pins.esp32SetPinMode': 'set pin [PIN] mode [MODE]',
            'microPythonEsp32.pins.esp32SetDigitalOutput': 'set digital pin [PIN] out [LEVEL]',
            'microPythonEsp32.pins.esp32SetPwmOutput': 'set pwm pin [PIN] out [OUT]',
            'microPythonEsp32.pins.esp32SetDACOutput': 'set dac pin [PIN] out [OUT]',
            'microPythonEsp32.pins.esp32ReadDigitalPin': 'read digital pin [PIN]',
            'microPythonEsp32.pins.esp32ReadAnalogPin': 'read analog pin [PIN]',
            'microPythonEsp32.pins.esp32ReadTouchPin': 'read touch pin [PIN]',
            'microPythonEsp32.pins.setServoOutput': 'set servo pin [PIN] out [OUT]',
            'microPythonEsp32.pins.esp32AttachInterrupt': 'attach interrupt pin [PIN] mode [MODE] executes',
            'microPythonEsp32.category.console': 'Console',
            'microPythonEsp32.console.consolePrint': 'print [TEXT] [EOL]',
            'microPythonEsp32.console.consoleInput': 'prompt [TEXT] and read input'
        },
        'ru': {
            'microPythonEsp32.modeMenu.input': 'input',
            'microPythonEsp32.modeMenu.output': 'output',
            'microPythonEsp32.modeMenu.inputPullup': 'input-pullup',
            'microPythonEsp32.modeMenu.inputPulldown': 'input-pulldown',
            'microPythonEsp32.levelMenu.high': 'high',
            'microPythonEsp32.levelMenu.low': 'low',
            'microPythonEsp32.InterrupModeMenu.risingEdge': 'rising edge',
            'microPythonEsp32.InterrupModeMenu.fallingEdge': 'falling edge',
            'microPythonEsp32.InterrupModeMenu.changeEdge': 'change edge',
            'microPythonEsp32.InterrupModeMenu.low': 'low level',
            'microPythonEsp32.InterrupModeMenu.high': 'high level',
            'microPythonEsp32.eolMenu.warp': 'warp',
            'microPythonEsp32.eolMenu.noWarp': 'no-warp',
            'microPythonEsp32.category.pins': 'Pins',
            'microPythonEsp32.pins.esp32SetPinMode': 'set pin [PIN] mode [MODE]',
            'microPythonEsp32.pins.esp32SetDigitalOutput': 'set digital pin [PIN] out [LEVEL]',
            'microPythonEsp32.pins.esp32SetPwmOutput': 'set pwm pin [PIN] out [OUT]',
            'microPythonEsp32.pins.esp32SetDACOutput': 'set dac pin [PIN] out [OUT]',
            'microPythonEsp32.pins.esp32ReadDigitalPin': 'read digital pin [PIN]',
            'microPythonEsp32.pins.esp32ReadAnalogPin': 'read analog pin [PIN]',
            'microPythonEsp32.pins.esp32ReadTouchPin': 'read touch pin [PIN]',
            'microPythonEsp32.pins.setServoOutput': 'set servo pin [PIN] out [OUT]',
            'microPythonEsp32.pins.esp32AttachInterrupt': 'attach interrupt pin [PIN] mode [MODE] executes',
            'microPythonEsp32.category.console': 'Console',
            'microPythonEsp32.console.consolePrint': 'print [TEXT] [EOL]',
            'microPythonEsp32.console.consoleInput': 'prompt [TEXT] and read input'
        },
        'zh-cn': {
            'microPythonEsp32.modeMenu.input': 'input',
            'microPythonEsp32.modeMenu.output': 'output',
            'microPythonEsp32.modeMenu.inputPullup': 'input-pullup',
            'microPythonEsp32.modeMenu.inputPulldown': 'input-pulldown',
            'microPythonEsp32.levelMenu.high': 'high',
            'microPythonEsp32.levelMenu.low': 'low',
            'microPythonEsp32.InterrupModeMenu.risingEdge': 'rising edge',
            'microPythonEsp32.InterrupModeMenu.fallingEdge': 'falling edge',
            'microPythonEsp32.InterrupModeMenu.changeEdge': 'change edge',
            'microPythonEsp32.InterrupModeMenu.low': 'low level',
            'microPythonEsp32.InterrupModeMenu.high': 'high level',
            'microPythonEsp32.eolMenu.warp': 'warp',
            'microPythonEsp32.eolMenu.noWarp': 'no-warp',
            'microPythonEsp32.category.pins': 'Pins',
            'microPythonEsp32.pins.esp32SetPinMode': 'set pin [PIN] mode [MODE]',
            'microPythonEsp32.pins.esp32SetDigitalOutput': 'set digital pin [PIN] out [LEVEL]',
            'microPythonEsp32.pins.esp32SetPwmOutput': 'set pwm pin [PIN] out [OUT]',
            'microPythonEsp32.pins.esp32SetDACOutput': 'set dac pin [PIN] out [OUT]',
            'microPythonEsp32.pins.esp32ReadDigitalPin': 'read digital pin [PIN]',
            'microPythonEsp32.pins.esp32ReadAnalogPin': 'read analog pin [PIN]',
            'microPythonEsp32.pins.esp32ReadTouchPin': 'read touch pin [PIN]',
            'microPythonEsp32.pins.setServoOutput': 'set servo pin [PIN] out [OUT]',
            'microPythonEsp32.pins.esp32AttachInterrupt': 'attach interrupt pin [PIN] mode [MODE] executes',
            'microPythonEsp32.category.console': 'Console',
            'microPythonEsp32.console.consolePrint': 'print [TEXT] [EOL]',
            'microPythonEsp32.console.consoleInput': 'prompt [TEXT] and read input'
        },
        'zh-tw': {
            'microPythonEsp32.modeMenu.input': 'input',
            'microPythonEsp32.modeMenu.output': 'output',
            'microPythonEsp32.modeMenu.inputPullup': 'input-pullup',
            'microPythonEsp32.modeMenu.inputPulldown': 'input-pulldown',
            'microPythonEsp32.levelMenu.high': 'high',
            'microPythonEsp32.levelMenu.low': 'low',
            'microPythonEsp32.InterrupModeMenu.risingEdge': 'rising edge',
            'microPythonEsp32.InterrupModeMenu.fallingEdge': 'falling edge',
            'microPythonEsp32.InterrupModeMenu.changeEdge': 'change edge',
            'microPythonEsp32.InterrupModeMenu.low': 'low level',
            'microPythonEsp32.InterrupModeMenu.high': 'high level',
            'microPythonEsp32.eolMenu.warp': 'warp',
            'microPythonEsp32.eolMenu.noWarp': 'no-warp',
            'microPythonEsp32.category.pins': 'Pins',
            'microPythonEsp32.pins.esp32SetPinMode': 'set pin [PIN] mode [MODE]',
            'microPythonEsp32.pins.esp32SetDigitalOutput': 'set digital pin [PIN] out [LEVEL]',
            'microPythonEsp32.pins.esp32SetPwmOutput': 'set pwm pin [PIN] out [OUT]',
            'microPythonEsp32.pins.esp32SetDACOutput': 'set dac pin [PIN] out [OUT]',
            'microPythonEsp32.pins.esp32ReadDigitalPin': 'read digital pin [PIN]',
            'microPythonEsp32.pins.esp32ReadAnalogPin': 'read analog pin [PIN]',
            'microPythonEsp32.pins.esp32ReadTouchPin': 'read touch pin [PIN]',
            'microPythonEsp32.pins.setServoOutput': 'set servo pin [PIN] out [OUT]',
            'microPythonEsp32.pins.esp32AttachInterrupt': 'attach interrupt pin [PIN] mode [MODE] executes',
            'microPythonEsp32.category.console': 'Console',
            'microPythonEsp32.console.consolePrint': 'print [TEXT] [EOL]',
            'microPythonEsp32.console.consoleInput': 'prompt [TEXT] and read input'
        }
    },
    'blocks': {
        'en': {},
        'ru': {},
        'zh-cn': {},
        'zh-tw': {}
    }
};
