/* eslint-disable quote-props */
/* eslint-disable max-len */
/**
 * Translation file for this resource.
 *
 * This file is generated by combining automatic extraction and manual translations:
 * - The "en" (English) section is automatically extracted from source files
 * - Other language sections can be manually translated or pulled from Transifex
 * - When regenerating, existing manual translations are preserved when the English
 *   source text hasn't changed
 *
 * Structure:
 * - interface: translations for name/description (used by GUI formatMessage)
 * - extensions: translations for extension blocks (used by VM formatMessage)
 * - blocks: translations for Blockly blocks (used by Blockly.Msg)
 */

export default {
    'interface': {
        'en': {
            'microPythonEsp32.description': 'Wi-Fi & Bluetooth control board with rich functions.',
            'microPythonEsp32.examples.blink.name': 'Blink',
            'microPythonEsp32.examples.blink.description': 'Make the on-board LED blink.',
            'microPythonEsp32.examples.button.name': 'Button',
            'microPythonEsp32.examples.button.description': 'Light up the LED while a push button is pressed.',
            'microPythonEsp32.examples.fade.name': 'Fade',
            'microPythonEsp32.examples.fade.description': 'Smoothly fade an LED in and out using PWM.',
            'microPythonEsp32.examples.knob.name': 'Knob',
            'microPythonEsp32.examples.knob.description': 'Control LED brightness with a potentiometer.',
            'microPythonEsp32.examples.servoSweep.name': 'Servo Sweep',
            'microPythonEsp32.examples.servoSweep.description': 'Sweep a servo back and forth between 0 and 180 degrees.',
            'microPythonEsp32.examples.consolePrint.name': 'Console Print',
            'microPythonEsp32.examples.consolePrint.description': 'Print messages to the MicroPython REPL console.'
        },
        'ru': {
            'microPythonEsp32.description': 'Wi-Fi & Bluetooth control board with rich functions.',
            'microPythonEsp32.examples.blink.name': 'Мигание',
            'microPythonEsp32.examples.blink.description': 'Заставьте встроенный светодиод мигать.',
            'microPythonEsp32.examples.button.name': 'Кнопка',
            'microPythonEsp32.examples.button.description': 'Зажигайте светодиод, пока нажата кнопка.',
            'microPythonEsp32.examples.fade.name': 'Плавное затухание',
            'microPythonEsp32.examples.fade.description': 'Плавное затухание светодиода с помощью ШИМ.',
            'microPythonEsp32.examples.knob.name': 'Регулятор',
            'microPythonEsp32.examples.knob.description': 'Регулировка яркости светодиода с помощью потенциометра.',
            'microPythonEsp32.examples.servoSweep.name': 'Развертка серво',
            'microPythonEsp32.examples.servoSweep.description': 'Поворот серво вперед и назад между 0° и 180°.',
            'microPythonEsp32.examples.consolePrint.name': 'Печать в консоль',
            'microPythonEsp32.examples.consolePrint.description': 'Печать сообщений в REPL-консоль MicroPython.'
        },
        'zh-cn': {
            'microPythonEsp32.description': 'Wi-Fi & Bluetooth control board with rich functions.',
            'microPythonEsp32.examples.blink.name': '闪烁',
            'microPythonEsp32.examples.blink.description': '让板载 LED 闪烁。',
            'microPythonEsp32.examples.button.name': '按键',
            'microPythonEsp32.examples.button.description': '按住按键时点亮 LED。',
            'microPythonEsp32.examples.fade.name': '呼吸灯',
            'microPythonEsp32.examples.fade.description': '用 PWM 让 LED 缓缓变亮再渐渐变暗。',
            'microPythonEsp32.examples.knob.name': '电位器调光',
            'microPythonEsp32.examples.knob.description': '用电位器调节 LED 的亮度。',
            'microPythonEsp32.examples.servoSweep.name': '舵机来回扫描',
            'microPythonEsp32.examples.servoSweep.description': '让舵机在 0° 到 180° 之间来回转动。',
            'microPythonEsp32.examples.consolePrint.name': '控制台输出',
            'microPythonEsp32.examples.consolePrint.description': '把消息打印到 MicroPython REPL 控制台。'
        },
        'zh-tw': {
            'microPythonEsp32.description': 'Wi-Fi & Bluetooth control board with rich functions.',
            'microPythonEsp32.examples.blink.name': '閃爍',
            'microPythonEsp32.examples.blink.description': '讓板載 LED 閃爍。',
            'microPythonEsp32.examples.button.name': '按鍵',
            'microPythonEsp32.examples.button.description': '按住按鍵時點亮 LED。',
            'microPythonEsp32.examples.fade.name': '呼吸燈',
            'microPythonEsp32.examples.fade.description': '用 PWM 讓 LED 緩緩變亮再漸漸變暗。',
            'microPythonEsp32.examples.knob.name': '電位器調光',
            'microPythonEsp32.examples.knob.description': '用電位器調節 LED 的亮度。',
            'microPythonEsp32.examples.servoSweep.name': '舵機來回掃描',
            'microPythonEsp32.examples.servoSweep.description': '讓舵機在 0° 到 180° 之間來回轉動。',
            'microPythonEsp32.examples.consolePrint.name': '終端輸出',
            'microPythonEsp32.examples.consolePrint.description': '將訊息列印到 MicroPython REPL 終端。'
        }
    },
    'extensions': {
        'en': {
            'microPythonEsp32.modeMenu.input': 'input',
            'microPythonEsp32.modeMenu.output': 'output',
            'microPythonEsp32.modeMenu.inputPullup': 'input-pullup',
            'microPythonEsp32.modeMenu.inputPulldown': 'input-pulldown',
            'microPythonEsp32.levelMenu.high': 'high',
            'microPythonEsp32.levelMenu.low': 'low',
            'microPythonEsp32.InterrupModeMenu.risingEdge': 'rising edge',
            'microPythonEsp32.InterrupModeMenu.fallingEdge': 'falling edge',
            'microPythonEsp32.InterrupModeMenu.changeEdge': 'change edge',
            'microPythonEsp32.InterrupModeMenu.low': 'low level',
            'microPythonEsp32.InterrupModeMenu.high': 'high level',
            'microPythonEsp32.eolMenu.warp': 'warp',
            'microPythonEsp32.eolMenu.noWarp': 'no-warp',
            'microPythonEsp32.category.pins': 'Pins',
            'microPythonEsp32.pins.setPinMode': 'set pin [PIN] mode [MODE]',
            'microPythonEsp32.pins.setDigitalOutput': 'set digital pin [PIN] out [LEVEL]',
            'microPythonEsp32.pins.setPwmOutput': 'set pwm pin [PIN] out [OUT]',
            'microPythonEsp32.pins.setDACOutput': 'set dac pin [PIN] out [OUT]',
            'microPythonEsp32.pins.readDigitalPin': 'read digital pin [PIN]',
            'microPythonEsp32.pins.readAnalogPin': 'read analog pin [PIN]',
            'microPythonEsp32.pins.readTouchPin': 'read touch pin [PIN]',
            'microPythonEsp32.pins.setServoOutput': 'set servo pin [PIN] out [OUT]',
            'microPythonEsp32.pins.attachInterrupt': 'attach interrupt pin [PIN] mode [MODE] executes',
            'microPythonEsp32.category.console': 'Console',
            'microPythonEsp32.console.consolePrint': 'print [TEXT] [EOL]',
            'microPythonEsp32.console.consoleInput': 'prompt [TEXT] and read input'
        },
        'ru': {
            'microPythonEsp32.modeMenu.input': 'input',
            'microPythonEsp32.modeMenu.output': 'output',
            'microPythonEsp32.modeMenu.inputPullup': 'input-pullup',
            'microPythonEsp32.modeMenu.inputPulldown': 'input-pulldown',
            'microPythonEsp32.levelMenu.high': 'high',
            'microPythonEsp32.levelMenu.low': 'low',
            'microPythonEsp32.InterrupModeMenu.risingEdge': 'rising edge',
            'microPythonEsp32.InterrupModeMenu.fallingEdge': 'falling edge',
            'microPythonEsp32.InterrupModeMenu.changeEdge': 'change edge',
            'microPythonEsp32.InterrupModeMenu.low': 'low level',
            'microPythonEsp32.InterrupModeMenu.high': 'high level',
            'microPythonEsp32.eolMenu.warp': 'warp',
            'microPythonEsp32.eolMenu.noWarp': 'no-warp',
            'microPythonEsp32.category.pins': 'Pins',
            'microPythonEsp32.pins.setPinMode': 'set pin [PIN] mode [MODE]',
            'microPythonEsp32.pins.setDigitalOutput': 'set digital pin [PIN] out [LEVEL]',
            'microPythonEsp32.pins.setPwmOutput': 'set pwm pin [PIN] out [OUT]',
            'microPythonEsp32.pins.setDACOutput': 'set dac pin [PIN] out [OUT]',
            'microPythonEsp32.pins.readDigitalPin': 'read digital pin [PIN]',
            'microPythonEsp32.pins.readAnalogPin': 'read analog pin [PIN]',
            'microPythonEsp32.pins.readTouchPin': 'read touch pin [PIN]',
            'microPythonEsp32.pins.setServoOutput': 'set servo pin [PIN] out [OUT]',
            'microPythonEsp32.pins.attachInterrupt': 'attach interrupt pin [PIN] mode [MODE] executes',
            'microPythonEsp32.category.console': 'Console',
            'microPythonEsp32.console.consolePrint': 'print [TEXT] [EOL]',
            'microPythonEsp32.console.consoleInput': 'prompt [TEXT] and read input'
        },
        'zh-cn': {
            'microPythonEsp32.modeMenu.input': 'input',
            'microPythonEsp32.modeMenu.output': 'output',
            'microPythonEsp32.modeMenu.inputPullup': 'input-pullup',
            'microPythonEsp32.modeMenu.inputPulldown': 'input-pulldown',
            'microPythonEsp32.levelMenu.high': 'high',
            'microPythonEsp32.levelMenu.low': 'low',
            'microPythonEsp32.InterrupModeMenu.risingEdge': 'rising edge',
            'microPythonEsp32.InterrupModeMenu.fallingEdge': 'falling edge',
            'microPythonEsp32.InterrupModeMenu.changeEdge': 'change edge',
            'microPythonEsp32.InterrupModeMenu.low': 'low level',
            'microPythonEsp32.InterrupModeMenu.high': 'high level',
            'microPythonEsp32.eolMenu.warp': 'warp',
            'microPythonEsp32.eolMenu.noWarp': 'no-warp',
            'microPythonEsp32.category.pins': 'Pins',
            'microPythonEsp32.pins.setPinMode': 'set pin [PIN] mode [MODE]',
            'microPythonEsp32.pins.setDigitalOutput': 'set digital pin [PIN] out [LEVEL]',
            'microPythonEsp32.pins.setPwmOutput': 'set pwm pin [PIN] out [OUT]',
            'microPythonEsp32.pins.setDACOutput': 'set dac pin [PIN] out [OUT]',
            'microPythonEsp32.pins.readDigitalPin': 'read digital pin [PIN]',
            'microPythonEsp32.pins.readAnalogPin': 'read analog pin [PIN]',
            'microPythonEsp32.pins.readTouchPin': 'read touch pin [PIN]',
            'microPythonEsp32.pins.setServoOutput': 'set servo pin [PIN] out [OUT]',
            'microPythonEsp32.pins.attachInterrupt': 'attach interrupt pin [PIN] mode [MODE] executes',
            'microPythonEsp32.category.console': 'Console',
            'microPythonEsp32.console.consolePrint': 'print [TEXT] [EOL]',
            'microPythonEsp32.console.consoleInput': 'prompt [TEXT] and read input'
        },
        'zh-tw': {
            'microPythonEsp32.modeMenu.input': 'input',
            'microPythonEsp32.modeMenu.output': 'output',
            'microPythonEsp32.modeMenu.inputPullup': 'input-pullup',
            'microPythonEsp32.modeMenu.inputPulldown': 'input-pulldown',
            'microPythonEsp32.levelMenu.high': 'high',
            'microPythonEsp32.levelMenu.low': 'low',
            'microPythonEsp32.InterrupModeMenu.risingEdge': 'rising edge',
            'microPythonEsp32.InterrupModeMenu.fallingEdge': 'falling edge',
            'microPythonEsp32.InterrupModeMenu.changeEdge': 'change edge',
            'microPythonEsp32.InterrupModeMenu.low': 'low level',
            'microPythonEsp32.InterrupModeMenu.high': 'high level',
            'microPythonEsp32.eolMenu.warp': 'warp',
            'microPythonEsp32.eolMenu.noWarp': 'no-warp',
            'microPythonEsp32.category.pins': 'Pins',
            'microPythonEsp32.pins.setPinMode': 'set pin [PIN] mode [MODE]',
            'microPythonEsp32.pins.setDigitalOutput': 'set digital pin [PIN] out [LEVEL]',
            'microPythonEsp32.pins.setPwmOutput': 'set pwm pin [PIN] out [OUT]',
            'microPythonEsp32.pins.setDACOutput': 'set dac pin [PIN] out [OUT]',
            'microPythonEsp32.pins.readDigitalPin': 'read digital pin [PIN]',
            'microPythonEsp32.pins.readAnalogPin': 'read analog pin [PIN]',
            'microPythonEsp32.pins.readTouchPin': 'read touch pin [PIN]',
            'microPythonEsp32.pins.setServoOutput': 'set servo pin [PIN] out [OUT]',
            'microPythonEsp32.pins.attachInterrupt': 'attach interrupt pin [PIN] mode [MODE] executes',
            'microPythonEsp32.category.console': 'Console',
            'microPythonEsp32.console.consolePrint': 'print [TEXT] [EOL]',
            'microPythonEsp32.console.consoleInput': 'prompt [TEXT] and read input'
        }
    },
    'blocks': {
        'en': {},
        'ru': {},
        'zh-cn': {},
        'zh-tw': {}
    }
};
